FROM --platform=linux/amd64 ubuntu:18.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cmake liblas-dev

ADD . /repo
WORKDIR /repo
RUN make -j8
RUN make test
